import { relations } from "drizzle-orm";
import {
  index,
  integer,
  jsonb,
  pgTable,
  real,
  text,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";

import { user } from "./auth";

/**
 * Learning content items (videos, articles, exercises, dialogues).
 * Each item has a CEFR difficulty level and topic tags.
 */
export const contentItem = pgTable(
  "content_item",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    title: text("title").notNull(),
    description: text("description").notNull(),
    type: text("type").notNull(), // "video" | "article" | "exercise" | "dialogue"
    cefrLevel: text("cefr_level").notNull(), // "A1" | "A2" | "B1" | "B2" | "C1" | "C2"
    sourceUrl: text("source_url"),
    thumbnailUrl: text("thumbnail_url"),
    duration: integer("duration"), // seconds, nullable
    tags: text("tags").array().notNull().default([]),
    metadata: jsonb("metadata"), // extra fields per type
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [
    index("content_item_cefr_idx").on(table.cefrLevel, table.type),
    index("content_item_tags_idx").on(table.tags),
  ]
);

/**
 * Cached 384-dim embedding for each content item.
 * Recomputed when content changes.
 */
export const contentEmbedding = pgTable(
  "content_embedding",
  {
    contentId: text("content_id")
      .primaryKey()
      .references(() => contentItem.id, { onDelete: "cascade" }),
    embedding: real("embedding").array().notNull(),
    modelVersion: text("model_version").notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("content_embedding_model_idx").on(table.modelVersion)]
);

/**
 * User interactions with content: view, like, bookmark, complete, share.
 * Used for collaborative filtering and engagement scoring.
 */
export const userInteraction = pgTable(
  "user_interaction",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    contentId: text("content_id")
      .notNull()
      .references(() => contentItem.id, { onDelete: "cascade" }),
    action: text("action").notNull(), // "view" | "like" | "bookmark" | "complete" | "share" | "dismiss"
    value: integer("value"), // e.g. percent watched, rating 1-5
    metadata: jsonb("metadata"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    unique("user_interaction_unique_idx").on(
      table.userId,
      table.contentId,
      table.action
    ),
    index("user_interaction_user_idx").on(table.userId, table.createdAt),
    index("user_interaction_content_idx").on(table.contentId, table.action),
  ]
);

/**
 * Pre-computed recommendation scores per user-content pair.
 * Generated by a background job; read at serving time.
 */
export const recommendationScore = pgTable(
  "recommendation_score",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    contentId: text("content_id")
      .notNull()
      .references(() => contentItem.id, { onDelete: "cascade" }),
    score: real("score").notNull(), // 0.0 - 1.0
    scoreType: text("score_type").notNull(), // "content" | "collaborative" | "hybrid" | "trending"
    reason: text("reason"), // human-readable why this was recommended
    createdAt: timestamp("created_at").defaultNow().notNull(),
    expiresAt: timestamp("expires_at"), // when this score should be recalculated
  },
  (table) => [
    unique("rec_score_user_content_idx").on(
      table.userId,
      table.contentId,
      table.scoreType
    ),
    index("rec_score_user_score_idx").on(
      table.userId,
      table.scoreType,
      table.score
    ),
    index("rec_score_expires_idx").on(table.expiresAt),
  ]
);

/**
 * User preference profile for recommendation tuning.
 * Explicit interests and goals, plus implicit signals.
 */
export const userPreference = pgTable("user_preference", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  interests: text("interests").array().notNull().default([]),
  goals: text("goals").array().notNull().default([]),
  preferredTypes: text("preferred_types").array().notNull().default([]), // "video" | "article" | ...
  preferredCefr: text("preferred_cefr"), // override auto-detected
  dailyGoal: integer("daily_goal").default(15).notNull(), // minutes
  notifications: jsonb("notifications").default({
    dailyReminder: true,
    newContent: true,
    progressUpdates: true,
  }),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

// Relations
export const contentItemRelations = relations(contentItem, ({ one, many }) => ({
  embedding: one(contentEmbedding, {
    fields: [contentItem.id],
    references: [contentEmbedding.contentId],
  }),
  interactions: many(userInteraction),
  recommendations: many(recommendationScore),
}));

export const userInteractionRelations = relations(
  userInteraction,
  ({ one }) => ({
    user: one(user, {
      fields: [userInteraction.userId],
      references: [user.id],
    }),
    content: one(contentItem, {
      fields: [userInteraction.contentId],
      references: [contentItem.id],
    }),
  })
);

export const recommendationScoreRelations = relations(
  recommendationScore,
  ({ one }) => ({
    user: one(user, {
      fields: [recommendationScore.userId],
      references: [user.id],
    }),
    content: one(contentItem, {
      fields: [recommendationScore.contentId],
      references: [contentItem.id],
    }),
  })
);

export const userPreferenceRelations = relations(userPreference, ({ one }) => ({
  user: one(user, {
    fields: [userPreference.userId],
    references: [user.id],
  }),
}));
